apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  db_user: cG9zdGdyZXMubHVhZHBud3JmdHBidHJ5cGl1aXM=
  db_password: S0NvSXJ0V3JYNXcxNTlEWA==
  db_host: YXdzLTAtdXMtZWFzdC0xLnBvb2xlci5zdXBhYmFzZS5jb20=
  db_port: NjU0Mw==
  db_name: cG9zdGdyZXM=
