name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t lucas${{ secrets.DOCKERHUB_USERNAME }}gmarques/nlw-api-journey:${{ steps.generate_sha.outputs.sha }} .

      - name: Push image
        run: | 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nlw-api-journey:${{ steps.generate_sha.outputs.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/nlw-api-journey:${{ steps.generate_sha.outputs.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/nlw-api-journey:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nlw-api-journey:latest